name: Deploy VitePress to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build VitePress
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          target-branch: blog_pages
          publish-dir: docs/.vitepress/dist
          token: ${{ secrets.GITHUB_TOKEN }}